/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Friends_viewer.graphql
 * @generated SignedSource<<d03ff775f7208e7bed59d8eb04c63804>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Friends_viewer = {|
  +id: string;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "Friends_viewer",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    },
    {
      "kind": "FragmentSpread",
      "name": "FriendsList_viewer",
      "args": null
    }
  ],
  "type": "User"
};

module.exports = fragment;
