/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Friend_viewer.graphql
 * @generated SignedSource<<0899d66cc12dbfb05faedb13eba1a28f>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Friend_viewer = {|
  +id: string;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "Friend_viewer",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    }
  ],
  "type": "User"
};

module.exports = fragment;
